# Generated by Django 4.2.7 on 2023-11-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
