# Generated by Django 4.2.7 on 2023-11-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_body_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
